openapi: 3.0.3
info:
  title: HR Tool
  description: HR Tool
  version: 1.0.0
servers:
  - url: 'http://localhost:8085'
paths:
  /vacation:
    get:
      description: Get vacation types
      operationId: getVacationTypes
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vacation"
  /employee/{id}/vacations/balance:
    get:
      description: Get employee vacations balance
      operationId: getEmployeeVacationsBalance
      parameters:
        - in: path
          required: true
          name: id
          description: Employee identifier
          schema:
            type: integer
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Balance"

  
components:
  schemas:
    Vacation:
      type: object
      properties:
        types:
          $ref: "#/components/schemas/VacationTypes"

    VacationTypes:
      type: array
      items:
        type: string
        enum:
          - casual
          - sickness
          - annual

    Balance:
      type: object
      properties:
        annual:
          type: integer
          example: 15
        sickness:
          type: integer
          example: 2